name: Deploy para EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código-fonte
      uses: actions/checkout@v2

    - name: Copiar arquivos para o servidor EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: .
        target: /home/ubuntu/clothes-wave-api

    - name: SSH para o servidor EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST` }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |

          cd /home/ubuntu/clothes-wave-api
          pm2 delete clothes-wave-api
          yarn
          sudo docker-compose up -d
          yarn typeorm migration:run
          pm2 start "sudo yarn dev" --name clothes-wave-api
